### ISSUE TITLE
SQL query results are inconsistent.

### ISSUE THREAD

**Issue by tuteng** [diennea/herddb#513] opened 2019-11-27 10:04 UTC
Is this a question, a feature request or a bug report?

**QUESTION**

Have you checked our documentation in the GitHub Wiki?
If you could not find an answer there, please consider asking your question on our mailing list at herddb-users@lists.herddb.org.

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

3. Provide any additional detail on your proposed use case for this feature.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
- [ ] [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 discription here, 
- [ ] [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 discription here,
- ...

**BUG REPORT**
Environment: herddb version 0.13.0, mybatis version 1.3.2 Reference: https://github.com/apache/pulsar-manager/blob/master/gradle.properties    
I can provide a more detailed code if necessary.

```
private void initRole(RoleInfoEntity roleInfoEntity) {
        roleInfoEntity.setRoleName("test-role-name");
        roleInfoEntity.setResourceType("tenants");
        roleInfoEntity.setResourceName("tenants");
        roleInfoEntity.setResourceVerbs("admin");
        roleInfoEntity.setDescription("This is tenants permissions");
    }

    private void validateRole(RoleInfoEntity role) {
        Assert.assertEquals(role.getRoleName(), "test-role-name");
        Assert.assertEquals(role.getResourceType(), "tenants");
        Assert.assertEquals(role.getResourceName(), "tenants");
        Assert.assertEquals(role.getResourceVerbs(), "admin");
        Assert.assertEquals(role.getDescription(), "This is tenants permissions");
    }

    @Test
    public void getRolesListTest() {
        RoleInfoEntity roleInfoEntity = new RoleInfoEntity();
        initRole(roleInfoEntity);

        rolesRepository.save(roleInfoEntity);

        Page<RoleInfoEntity> rolesList = rolesRepository.findRolesList(1, 10);
        rolesList.count(true);
        rolesList.getResult().forEach((role) -> {
            validateRole(role);
            rolesRepository.delete(role.getRoleName());
        });
```

1. Please describe the issue you observed:

- What did you do?
Create table:
```
CREATE TABLE IF NOT EXISTS roles (
  role_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_name varchar(256) NOT NULL,
  description varchar(128),
  resource_type varchar(48),
  resource_name varchar(48),
  resource_verbs varchar(256),
  UNIQUE (role_name)
);
```
Insert data and query data:
Query SQL
```
@Select("SELECT role_id AS roleId, role_name AS roleName, description, resource_type AS resourceType," +
            "resource_name AS resourceName, resource_verbs AS resourceVerbs FROM roles")
```

![image](https://user-images.githubusercontent.com/1907867/69713270-364f4d00-113f-11ea-8ca0-31bb7f9eb13e.png)

Insert data and query data:
Query SQL
```
@Select("SELECT role_name AS roleName, role_id AS roleId, description, resource_type AS resourceType," +
            "resource_name AS resourceName, resource_verbs AS resourceVerbs FROM roles")
```

![image](https://user-images.githubusercontent.com/1907867/69713501-9b0aa780-113f-11ea-968b-1b8a88418119.png)
As you can see, when I move field `role_id` to field `role_name`, I can normally query the results.

- What did you expect to see?
Two SQL queries have the same result

- What did you see instead?

**Comment by eolivelli** [comment] 2019-11-27 10:15
@tuteng
we are looking into this problem.

**Comment by eolivelli** [comment] 2019-11-27 11:04
I have found the cause of the problem.
MyBatis accesses JDBC ResultSets using "column names" and in the particular case of the query that seems to not return results we are losing the aliases, this is because we are falling into a specific code path that does not keep aliases (IdentityProjection).

The fix should be quite simple, and hopefully we can preserve the zero-copy feature in this specific case.
In fact in this case we are accessing the table exactly in the same order as in the physical layout of the record, so we do not need to perform in memory copies. The problem is that we are losing the alias names, we can keep them, in the worst case we will fall into ZeroCopyProjection.

We usually do not see this problem in other applications  probably because they do not use ResultSet#getXXX(String xxx).

**Comment by eolivelli** [comment] 2019-11-27 11:46
@tuteng I have sent a fix for this issue:  #514

**Comment by eolivelli** [comment] 2019-11-27 11:47
@diegosalvi  @amitvc  PTAL, it would be good to cherry pick to 0.13 branch and cut a point release this week

**Comment by tuteng** [comment] 2019-11-27 11:58
Thank you very much for your quick response. @eolivelli @diegosalvi @amitvc

**Closed** 2019-11-27 16:12 UTC
Labels: bug

**Comment by eolivelli** [comment] 2019-11-29 16:24
Hi @tuteng 
0.13.1 release is available on Maven central
https://github.com/diennea/herddb/releases/tag/v0.13.1

it fixes this problem
