### ISSUE TITLE
Select all from a non-existing table

### ISSUE THREAD

**Issue by FLion97** [diennea/herddb#507] opened 2019-11-13 14:04 UTC
**BUG REPORT**

1. Please describe the issue you observed:
When trying to select all the objects from a table that doesn't exist, the database will respond with:
`Executing query:SELECT * FROM mimmino
ERROR:java.sql.SQLException: herddb.model.StatementExecutionException: From line 1, column 15 to line 1, column 21: Object 'MIMMINO' not found
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:343)
        at herddb.server.ServerSideConnectionPeer.handleOpenScanner(ServerSideConnectionPeer.java:445)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:181)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)`
instead of showing simple response to the error (so the program won't check if your SQL syntax is correct before executing it)

**Comment by eolivelli** [comment] 2019-11-13 14:08
This looks like a duplicate of  #491 , doesn't it ?

**Comment by aluccaroni** [comment] 2019-11-25 11:10
Closing as duplicate. @FLion97 let us know if we missed something

**Closed by aluccaroni** 2019-11-25 11:10 UTC
Labels: duplicate
