### ISSUE TITLE
FOR UPDATE not supported

### ISSUE THREAD

**Issue by rmannibucau** [diennea/herddb#631] opened 2020-06-26 06:52 UTC
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Standard SQL support FOR UPDATE, ex:

    SELECT SEQUENCE_VALUE FROM OPENJPA_SEQUENCE_TABLE WHERE ID = ? FOR UPDATE

HerdDB does not.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

This prevents to use several JPA mapper without workarounds.

**Comment by eolivelli** [comment] 2020-06-26 06:58
Thank you @rmannibucau for reporting this issue

Looks like a duplicate of #228 
It depends of a low hanging issue on Calcite, see [CALCITE-2395](https://issues.apache.org/jira/browse/CALCITE-2395)
I will try to resume the work con CALCITE-2395.

A possible workaround would be to use AUTO_INCREMENT, but maybe this is not the case with OpenJPA

**Comment by rmannibucau** [comment] 2020-06-26 07:31
@eolivelli agre it is a duplicate. The workaround is not openjpa specific - all jpa providers will do it, there are a few strategies for prim key generations and using a table is a spec one - just the default for openjpa.

**Closed** 2020-06-30 13:47 UTC
Labels: duplicate
