### ISSUE TITLE
Problems with Calcite 1.21 that causes FilterJoinRule to causes Index out of bound error.

### ISSUE THREAD

**Issue by amitvc** [diennea/herddb#479] opened 2019-10-01 17:37 UTC
I am creating an issue to track calcite bug https://issues.apache.org/jira/browse/CALCITE-3347 that I reported few weeks back during upgrade to Calcite 1.21. Queries such as this "SELECT * FROM tblspace1.tsql where n1=? and k1 in (SELECT k1 FROM tblspace1.tsql where n1=?)" are broken because of FilterJoinRule exception being thrown. Please see the details in the Calcite ticket I have mentioned above.

**Comment by eolivelli** [comment] 2019-10-04 13:13
@amitvc it seems that https://github.com/apache/calcite/pull/1459 has been committed to Calcite master.

Do you have cycles to try to see if our test is fixed ? then we can report on JIRA CALCITE-3347 that our case is now solved.

I am planning to setup a CI job that tests HerdDB against latest Calcite master

**Comment by amitvc** [comment] 2019-10-07 20:07
@eolivelli I will check tonight.

**Comment by eolivelli** [comment] 2019-10-07 20:09
@amitvc today @diegosalvi saw important regressions on nightly builds of a downstream project, and it seems that the problem is related to the upgrade of Calcite

I hope he will post the details soon, I suspect that the problem is about JOINs.

**Comment by amitvc** [comment] 2019-10-07 21:03
@eolivelli @diegosalvi I look forward to your update. I can investigate what in calcite broke the regression.

**Comment by eolivelli** [comment] 2019-10-07 21:05
@amitvc thank you

**Comment by eolivelli** [comment] 2019-10-08 07:59
@amitvc 
This is the bad query:
```
SELECT M.MSG_ID FROM q2.q2_MESSAGE M WHERE 1=1 AND (M.MSG_ID IN (SELECT H.MSG_ID FROM q2.q2_HEADER AS H WHERE H.FIELD_NAME='From' AND H.FIELD_VALUE LIKE ?)) AND (M.RECIPIENT LIKE ?)
```

this is the error:
```
SEVERE: NettyChannel{name=unnamed, id=22, socket=[id: 0x1db8b5c5, L:local:127.0.0.1:1308:false - R:local:E:e9fb99cb] pending 0 msgs}: error java.lang.RuntimeException: Error while applying rule FilterJoinRule:FilterJoinRule:filter, args [rel#5031:EnumerableFilter.ENUMERABLE.[](input=RelSubset#5029,condition=LIKE($3, ?1)), rel#5058:EnumerableHashJoin.ENUMERABLE.[](left=RelSubset#3035,right=RelSubset#3202,condition==($0, $20),joinType=semi)]
java.lang.RuntimeException: Error while applying rule FilterJoinRule:FilterJoinRule:filter, args [rel#5031:EnumerableFilter.ENUMERABLE.[](input=RelSubset#5029,condition=LIKE($3, ?1)), rel#5058:EnumerableHashJoin.ENUMERABLE.[](left=RelSubset#3035,right=RelSubset#3202,condition==($0, $20),joinType=semi)]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:235)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:631)
	at herddb.sql.CalcitePlanner.runPlanner(CalcitePlanner.java:520)
	at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:288)
	at herddb.server.ServerSideConnectionPeer.handleOpenScanner(ServerSideConnectionPeer.java:445)
	at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:181)
	at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at org.apache.calcite.rex.RexUtil$FixNullabilityShuttle.visitInputRef(RexUtil.java:2529)
	at org.apache.calcite.rex.RexUtil$FixNullabilityShuttle.visitInputRef(RexUtil.java:2518)
	at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:112)
	at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:149)
	at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:101)
	at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:34)
	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191)
	at org.apache.calcite.rex.RexShuttle.apply(RexShuttle.java:277)
	at org.apache.calcite.rex.RexShuttle.mutate(RexShuttle.java:239)
	at org.apache.calcite.rex.RexShuttle.apply(RexShuttle.java:257)
	at org.apache.calcite.rex.RexUtil.fixUp(RexUtil.java:1635)
	at org.apache.calcite.rel.rules.FilterJoinRule.perform(FilterJoinRule.java:284)
	at org.apache.calcite.rel.rules.FilterJoinRule$FilterIntoJoinRule.onMatch(FilterJoinRule.java:383)
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:208)
	... 12 more
```

**Comment by eolivelli** [comment] 2019-10-08 08:08
@amitvc I confirm that with current Calcite master on 1.22.0-SNAPSHOT
the system works perfectly.

I will ask for a release on Calcite dev list, otherwise we must revert the upgrade of Calcite until they perform a new release.

**Comment by eolivelli** [comment] 2019-10-08 08:16
I am preparing a revert, because we have downstream projects integration tests against current HerdDB SNAPSHOT version that are failing
https://github.com/diennea/herddb/pull/482

I have sent an email on Calciate dev list

**Comment by amitvc** [comment] 2019-10-20 01:07
@eolivelli  I have created a pull request with Calcite 1.22. All tests are passing.
https://github.com/diennea/herddb/pull/487

**Closed** 2020-03-05 17:48 UTC
Labels: component/calcite
