### ISSUE TITLE
Auto Increment syntax doesn't work

### ISSUE THREAD

**Issue by damn-fox** [diennea/herddb#504] opened 2019-11-13 13:30 UTC
This statement with PRIMARY_KEY at the end doesn't work.
CREATE TABLE test_ino (iddino int NOT NULL AUTO_INCREMENT,stringhina varchar(255),datina datetime,charrino char(1),blobbino blob,booleanino tinyint(1) ,**PRIMARY KEY** (iddino))

This statement will work.
CREATE TABLE test_ino (iddino int NOT NULL **PRIMARY KEY** AUTO_INCREMENT,stringhina varchar(255),datina datetime,charrino char(1),blobbino blob,booleanino tinyint(1))

**Comment by aluccaroni** [comment] 2019-11-18 11:59
This looks like a duplicate of https://github.com/diennea/herddb/issues/468

On which version of HerdDB did you reproduce this issue?

**Comment by aluccaroni** [comment] 2019-11-25 11:11
Closing as duplicate. @damn-fox let us know if we missed something or if you are able to reproduce on latest version

**Closed by aluccaroni** 2019-11-25 11:11 UTC
Labels: duplicate
