### ISSUE TITLE
I can't create tables after the creation of a wrong tablespace with special characters

### ISSUE THREAD

**Issue by FLion97** [diennea/herddb#509] opened 2019-11-13 14:43 UTC
**BUG REPORT**
1. Please describe the issue you observed:
After I've created a tablespace with a special character, I can't neither create tables neither see them in the UI
Before: 
`ERROR:java.sql.SQLException: herddb.model.StatementExecutionException: unable to parse query EXECUTE createtablespace fagiano¶½
        at herddb.sql.DDLSQLPlanner.parseStatement(DDLSQLPlanner.java:237)
        at herddb.sql.DDLSQLPlanner.translate(DDLSQLPlanner.java:220)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:244)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:706)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:138)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 33.  Encountered: "\u00b6" (182), after : ""
        at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:3060)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:16085)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_131(CCJSqlParser.java:13556)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_78(CCJSqlParser.java:14301)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_78(CCJSqlParser.java:10407)
        at net.sf.jsqlparser.parser.CCJSqlParser.PrimaryExpression(CCJSqlParser.java:6053)
        at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseXor(CCJSqlParser.java:5903)
        at net.sf.jsqlparser.parser.CCJSqlParser.MultiplicativeExpression(CCJSqlParser.java:5859)
        at net.sf.jsqlparser.parser.CCJSqlParser.AdditiveExpression(CCJSqlParser.java:5820)
        at net.sf.jsqlparser.parser.CCJSqlParser.ConcatExpression(CCJSqlParser.java:5753)
        at net.sf.jsqlparser.parser.CCJSqlParser.BitwiseAndOr(CCJSqlParser.java:5777)
        at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpression(CCJSqlParser.java:5745)
        at net.sf.jsqlparser.parser.CCJSqlParser.SimpleExpressionList(CCJSqlParser.java:5629)
        at net.sf.jsqlparser.parser.CCJSqlParser.Execute(CCJSqlParser.java:7427)
        at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:182)
        at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
        at herddb.sql.DDLSQLPlanner.parseStatement(DDLSQLPlanner.java:235)
        ... 11 more`

And when i tired to create a new table:
`herd: CREATE TABLE gino
Executing query:CREATE TABLE gino
ERROR:java.sql.SQLException: java.util.concurrent.TimeoutException: io-error while waiting for reply: java.io.IOException: comunication channel is closed. Cannot wait for pending messages, socket=[id: 0xe2ecc8b0, L:0.0.0.0/0.0.0.0:52860]`

**Comment by aluccaroni** [comment] 2019-11-18 16:31
The error is related to the parsing of the "create tablespace" query, in fact the tablespace wasn't even created.

In this case I think this could be a duplicate of #491 (the problem is the parsing and

**Comment by aluccaroni** [comment] 2019-11-25 11:10
Closing as duplicate. @FLion97 let us know if we missed something

**Closed by aluccaroni** 2019-11-25 11:10 UTC
Labels: duplicate
